/*
 * This source file was generated by the Gradle 'init' task
 */
package com.voyago;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class VoyagoTest {
    @Test void appHasAGreeting() {
        Voyago classUnderTest = new Voyago();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
