/*
 * This source file was generated by the Gradle 'init' task
 */
package com.voyago;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Voyago {
    public static void main(String[] args) {
        SpringApplication.run(Voyago.class, args);
    }
}
